# Ruby 1.8.7 doesn't work on the default distribution
dist: trusty

language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.2


# todo - Remove this once TravisCI fixes their bundler issue (https://github.com/alphagov/govuk_template/pull/186)
before_install:
  - gem install bundler -v 1.9.10

script: bundle exec rake cucumber_analytics:ci_build
